name: MATRIX-DEMO-WORKFLOW
on: push
jobs:
  build:
    strategy:
      matrix:
        node-v: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Get-Code
        uses: actions/checkout@v2
      - name: Install-NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-v}}
      - name: Install-Dependencies
        run: npm ci
      - name: Build-Project
        run: npm run build
