name: MATRIX-DEMO-WORKFLOW
on: push
jobs:
  build:
    strategy:
      matrix:
        node-v: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-v: 18
            os: ubuntu-latest
        exclude:
          - node-v: 12
            os: windows-latest
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Get-Code
        uses: actions/checkout@v2
      - name: Install-NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-v}}
      - name: Install-Dependencies
        run: npm ci
      - name: Build-Project
        run: npm run build
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
